# Generated by Django 6.0.4 on 2026-04-21 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("PORTERIA", "Portería"),
                            ("DESPACHOS", "Despachos"),
                            ("PARQUEADERO", "Parqueadero"),
                            ("CARGUE", "Puerta de Cargue"),
                            ("FACTURACION", "Facturación"),
                            ("SALIDA", "Salida"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("orden", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Transportista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qr", models.CharField(max_length=50, unique=True)),
                (
                    "qr_imagen",
                    models.ImageField(blank=True, null=True, upload_to="qrs/"),
                ),
                ("placa", models.CharField(max_length=20)),
                ("conductor", models.CharField(max_length=100)),
                ("empresa", models.CharField(max_length=100)),
                ("fecha_ingreso", models.DateTimeField(auto_now_add=True)),
                (
                    "area_actual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transportistas_actuales",
                        to="operaciones.area",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_ingreso"],
            },
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="operaciones.area",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transportista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="operaciones.transportista",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_hora"],
            },
        ),
    ]
