# Generated by Django 6.0.4 on 2026-05-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operaciones", "0003_movimiento_tipo_registroarea"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportista",
            name="fecha_salida",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
