# Generated by Django 6.0.4 on 2026-05-08 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operaciones", "0004_transportista_fecha_salida"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CausalNovedadCargue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="RangoCubicaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("cubicaje_min", models.DecimalField(decimal_places=2, max_digits=8)),
                ("cubicaje_max", models.DecimalField(decimal_places=2, max_digits=8)),
                ("minutos_estandar", models.PositiveIntegerField()),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["cubicaje_min"],
            },
        ),
        migrations.AddField(
            model_name="asignacioncargue",
            name="cubicaje",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.CreateModel(
            name="NovedadCargue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("activa", models.BooleanField(default=True)),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "asignacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="novedades",
                        to="operaciones.asignacioncargue",
                    ),
                ),
                (
                    "causal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="novedades",
                        to="operaciones.causalnovedadcargue",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="novedades_cargue_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
